config/routes.rb
Rails.application.routes.draw do
  root 'ideas#index'

  resources :users, only: [:create, :edit, :update, :destroy]
  resources :sessions, only: [:create, :destroy]
  resources :ideas, only: [:create, :show, :edit, :new, :update, :destroy] do
    member do
      put "like" => "ideas#upvote"
      put "unlike" => "ideas#downvote"
    end
  end

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
    acts_as_votable cacheable_strategy: :update_columns
    has_one_attached :picture
    belongs_to :user

    validates :title, presence: true, length: {maximum: 50}
    validates :text, presence: true, length: {maximum: 255}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true,length: { minimum: 4, maximun: 20 }, format: { without: /\s/ }
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, :presence => true,:confirmation => true,:length => {:within => 6..40}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
  
    def current_user
      if session[:user_id]
        @current_user ||= User.find(session[:user_id])
      else
        @current_user = nil
      end
    end
  end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  before_action :set_idea, only: [:edit, :destroy, :update, :upvote, :downvote]

  def index
    @ideas = Idea.all.order :cached_votes_up => :desc
  end

  def new
    if user_logged
      @idea = Idea.new
    else
      redirect_to root_path
    end
  end

  def create
    @idea = Idea.new idea_params
    if @idea.save
      redirect root_path, "Ideia salva com sucesso"
    else
      flash.now[:alert] = "Erro! verifique os campos"
      render :new
    end
  end

  def edit
    if user_logged
      render :edit
    else
      redirect root_path 
    end
  end

  def update
    if @idea.update idea_params
        redirect root_path, "Ideia atualizada com sucesso"
    else
        render :edit
    end
  end

  def destroy
    if user_logged
      @idea.destroy
      @idea.picture.purge
      redirect root_path
    else
      redirect root_path
    end
  end

  def upvote
    @idea.upvote_from current_user
    redirect root_path
  end

  def downvote
    @idea.downvote_from current_user
    redirect root_path
  end

  private 

  def idea_params
    params.require(:idea).
      permit(:title, :text, :picture).
      merge(:user_id => current_user.id)
  end

  def set_idea
    id = params[:id]
    @idea = Idea.find(id)
  end

  def user_logged  
    session[:user_id]
  end

  def redirect(path, alert = nil)
    redirect_to path, notice: alert
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        if session[:user_id]
            redirect_to root_path
        end
    end

    def create
        user = User.find_by_email(params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_url, notice: "Logged in!"
        else
            flash.now[:alert] = "Email ou password é invalido"
        render "new"
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_url, notice: "Logged out!"
        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'Usuario criado com sucesso.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    if session[:user_id].to_i != params[:id].to_i
      redirect_to root_path
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: 'Usuario atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if session[:user_id].to_i == params[:id].to_i
      @user.destroy
      session.delete(:user_id)
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Usuario deletado com sucesso.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<%= stylesheet_link_tag 'form', media: 'all' %>

<div class="container mx-auto">
    <div class="py-1 wrapper">

      <div class="form-wrapper">
          <%= form_for @idea do |f| %>
            <fieldset class="section is-active">
              <div class="fields"> 

                <%= f.label "Titulo*" %>
                <%= f.text_field :title %>
                <small id="emailHelp" class="form-text text-muted">Maximo 50 caracteres</small>

                <%= f.label "Descrição*" %>
                <%= text_area(:idea, :text, class: 'form-control textarea', type:"textarea") %>
                <small id="emailHelp" class="form-text text-muted">Maximo de 240 caracteres</small>

                <%= f.file_field :picture %>
                <small id="emailHelp" class="form-text text-muted">Imagem opcional</small>
                <%if flash[:alert]%>
                <div class="alert alert-danger">
                  <strong>Erro encontrado no preenchimento</strong>
                </div>
                <%end%>
              </div>
          <div class="actions">
            <%= f.submit 'Adicionar', class: "submit " %>
          </div>
          </fieldset>
        <% end %>
      </div>
    </div>
  </div>

app/views/ideas/edit.html.erb
<%= render partial: 'form'%>

app/views/ideas/index.html.erb
<%= stylesheet_link_tag "ideas", :media => "all" %>

  <main>
    <section class="cards">
      <% @ideas.each do | idea |%>
      <article class="hover">
            <% if idea.picture.attached? %>
                <figure tabindex=1>
                  <img class="imagem-idea" src="<%=(url_for(idea.picture))%>">
                </figure>
                <% end%>
                <% if current_user %>
                  <%= link_to image_tag("remove.png", class: "remove-img"), idea_path(idea), :method => :delete, class:"remove-button"%>
                  <%= link_to image_tag("edit.png", class: "remove-img"), edit_idea_path(idea), class:"edit-button"%> 
                <% end %>
            <div class="text_post">
                <h1 class="title-post"><%= idea.title%></h1>
                <p class="idea-text"><%= idea.text%></p>
            
            </div>
            <div class="enquete">
            <ul class="lista-enquete">
              <li class="enquente-vote upvote">
                <%= link_to like_idea_path(idea), method: :put do %>
                  <strong>Aprovar - <%= idea.get_upvotes.size%></strong> 
                  </button> 
                <% end %>
              </li>
              <li class="enquente-vote downvote">
                <%= link_to unlike_idea_path(idea), method: :put do %>
                   <strong>Reprovar - <%= idea.get_downvotes.size%></strong> 
                <% end %>
              </li>
            </ul>
            </div>
      </article>
      <% end %>
    </section>

  </main>

app/views/ideas/new.html.erb
<%= render 'form', idea: @idea %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'reset', media: 'all' %>
    <%= stylesheet_link_tag 'bootstrap_and_overrides', media: 'all' %>
    <%= stylesheet_link_tag 'font', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="text-center">
  <nav class="navbar navbar-expand navbar-light bg-light" >
  <a class="navbar-brand" href=<%= root_path %>>Idea Board</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if current_user %>

      <li class="nav-item">
        <a class="nav-link active" href=<%= new_idea_path %>>Adicionar ideia</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=<%= edit_user_path(current_user) %>>Perfil </a>
      </li> 
       <li class="nav-item">
        <a class="nav-link" href=<%= logout_path %>>Logout </a>
      </li> 
      <% else %>
      <li class="nav-item">
        <a class="nav-link" href=<%= login_path %>>Sign in </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=<%= signup_path %>>Sign up </a>
      </li>
      <%end%>
      <li class="nav-item">
        <%if flash[:notice]%>
          <div class="nav-link notice" role="alert"><%=flash[:notice]%></div>
        <% end %>
      </li>
       
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="container mx-auto">
    <div class="py-1 wrapper">
      <div class="form-wrapper">
         <%= form_with(model: user, local: true) do |form| %>
            <fieldset class="section is-active">
            <div class="fields">
            <%= form.label :username %>
            <%= form.text_field :username %>
            <small id="emailHelp" class="form-text text-muted left">Mínimo de 4 caracteres</small>

            <%= form.label :email %>
            <%= form.text_field :email, placeholder: "exemplo@email.com" %>

            <%= form.label "Senha" %>
            <%= form.password_field :password%>
            <small id="emailHelp" class="form-text text-muted">Mínimo de 6 caracteres</small>

            <%= form.label "Confirme a senha" %>
            <%= form.password_field :password_confirmation %>
            <% if user.errors.any? %>
          <div class="alert alert-danger">
            <strong>Erro encontrado no preenchimento</strong>
          </div>
          <% end %>
          </div>
            <% if current_user %>
              <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Tem certeza?' }, class:"destoy-button" %>
            <% end %>
            <%= form.submit 'Criar', class: "submit button" %>
          </fieldset>
        <% end %>
      </div>
    </div>
  </div>
  

app/views/users/edit.html.erb
<%= stylesheet_link_tag 'form', media: 'all' %>

<%= render 'form', user: @user %>

app/views/users/new.html.erb
<%= stylesheet_link_tag 'form', media: 'all' %>

<%= render 'form', user: @user %>